- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - ufw
      - fail2ban
      - qemu-guest-agent
      - acl
      - python3-psycopg2
    state: present

# - name: Enable qemu-guest-agent
#   systemd:
#     name: qemu-guest-agent
#     enabled: yes
#     state: started
#   ignore_errors: yes  # Le canal virtio est activé via Terraform séparément

- name: Disable password SSH auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: Set timezone
  timezone:
    name: Europe/Paris