all:
  vars:
    ansible_user: cia
    ansible_ssh_private_key_file: /tmp/cia_infra

  hosts:
    proxmox_s1:
      ansible_host: "{{ lookup('env', 'PROXMOX_S1_IP') }}"
      ansible_user: root
      ansible_ssh_private_key_file: /tmp/cia_infra
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    proxmox_s2:
      ansible_host: "{{ lookup('env', 'PROXMOX_S2_IP') }}"
      ansible_user: root
      ansible_ssh_private_key_file: /tmp/cia_infra
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  children:
    # ── Site 1 ───────────────────────────────────────────────────────────────
    site1:
      hosts:
        router_s1:
          ansible_host: 10.1.0.1
          router_role: server
          wan_interface: eth0
          lan_interface: eth1
          lan_network: "10.1.0.0/24"
        netbox:
          ansible_host: 10.1.0.10
        elasticsearch:
          ansible_host: 10.1.0.20

    # ── Site 2 ───────────────────────────────────────────────────────────────
    site2:
      hosts:
        router_s2:
          ansible_host: 10.2.0.1
          router_role: client
          wan_interface: eth0
          lan_interface: eth1
          lan_network: "10.2.0.0/24"
        bastion:
          ansible_host: 10.2.0.5
        webserver:
          ansible_host: 10.2.0.30
