all:
  vars:
    ansible_user: cia
    ansible_ssh_private_key_file: /tmp/cia_infra

  children:
    site1:
      hosts:
        netbox:
          ansible_host: 10.1.0.10
        elasticsearch:
          ansible_host: 10.1.0.20

    site2:
      hosts:
        bastion:
          ansible_host: 10.2.0.5
        webserver:
          ansible_host: 10.2.0.30
          ansible_ssh_common_args: >
            -o ProxyJump=cia@10.2.0.5
            -o StrictHostKeyChecking=no