---
- name: Bootstrap Proxmox (NAT + port forwarding)
  hosts: proxmox
  become: true
  roles: [proxmox-bootstrap]

- name: Common setup all VMs
  hosts: all:!proxmox
  become: true
  roles: [common]

- name: Deploy NetBox
  hosts: netbox
  become: true
  roles: [netbox]

- name: Deploy Elasticsearch + Kibana
  hosts: elasticsearch
  become: true
  roles: [elasticsearch, filebeat]

- name: Deploy Bastion
  hosts: bastion
  become: true
  roles: [bastion, openvpn, filebeat]

- name: Deploy Webserver
  hosts: webserver
  become: true
  roles: [webserver, filebeat]